services:
  rag-agent:
    build: .
    volumes:
      - ./data:/app/data
      - ./embeddings:/app/embeddings
    env_file:
      - .env
    ports:
      - "8000:8000"  # API açacaksan buradan erişirsin
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: bg3_assistant
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
